version: '3.9'
services:
  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
  web:
    build: .
    environment:
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/1
      - REDIS_URL=redis://redis:6379/2
    depends_on:
      - redis
    ports:
      - "8000:8000"
  worker:
    build: .
    command: celery -A tasks.celery_app worker --loglevel=INFO
    environment:
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/1
      - REDIS_URL=redis://redis:6379/2
    depends_on:
      - redis


